services:
  portal-server:
    container_name: staff_training
    environment:
      - TZ=Europe/Moscow
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: /target/training-backend-0.0.1-SNAPSHOT.jar
    env_file:
      - .env
    ports:
      - 8181:8181
    volumes:
      - spring-log:/home/logs
    restart: always

volumes:
  spring-log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/home/astra/logs/staff-training"

